#FROM ubuntu:focal
FROM r-base:4.0.5


RUN apt-get -y update && apt-get install cmake -y
RUN apt-get install -y nasm
RUN apt-get install libblas-dev liblapack-dev -y
RUN apt-get install gdb -y

RUN R -e "install.packages(\"RInside\", repos=\"https://cran.rstudio.com\")" --no-save

RUN R -e "if (!requireNamespace(\"BiocManager\", quietly = TRUE)) {install.packages(\"BiocManager\", repo=\"http://cran.rstudio.com/\")}" --no-save 

RUN R -e "BiocManager::install()"  --no-save 
RUN R -e "BiocManager::install(c(\"gRbase\", \"RBGL\", \"Rgraphviz\", \"gRain\"))" --no-save 
RUN R -e "install.packages(\"pcalg\", repos=\"https://cran.rstudio.com\")" --no-save
RUN R -e "packageurl <- \"https://cran.r-project.org/src/contrib/Archive/BiDAG/BiDAG_2.0.0.tar.gz\" ; install.packages(packageurl, repos=NULL, type=\"source\")" --no-save

WORKDIR /order_pgibbs
COPY . .
#RUN make

#RUN apt install update-manager-core -y
#RUN apt upgrade 


#RUN apt-get install libboost-all-dev -y


# RUN apt install update-manager-core

# RUN apt install r-base
# RUN "R install RInside"

# COPY ./MCKL/include/mckl/ /usr/local/include/mckl
# COPY ./vSMC/include/vsmc/ /usr/local/include/vsmcß

# ENV CXXFLAGS -std=c++14
# #WORKDIR /usr/src/myapp/MCKL/build

# WORKDIR /usr/src/myapp 

# #RUN apt-get install build-essential

# LABEL Name=ordersmc Version=1.0
