version = 1.3.1-nosetuid
docker_build: ;  docker build -t bpimages/orderpruning .
docker_push: ;  docker push bpimages/orderpruning
sing_build: ; apptainer pull --dir ~/singularity_images/ docker://bpimages/orderpruning:$(version)
sing_push: ; apptainer push -U ~/singularity_images/orderpruning_$(version).sif library://felixleopoldo/bn/orderpruning:$(version)