docker_build: ;  docker build -t onceltuca/orderpruning .
docker_push: ;  docker push onceltuca/orderpruning
singu_build: ; singularity pull --dir ~/singularity_images/ docker://onceltuca/orderpruning:1.2.1
sing_push: ; singularity push -U ~/singularity_images/orderpruning_1.2.1.sif library://felixleopoldo/bn/orderpruning:1.2.1